import LateralBar from "./components/LateralBar";
import Menu from "./components/Menu";
import Header from "./components/Header";
import Footer from "./components/Footer";
import "./globals.css";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className="sm:dark:gradient-custom-light min-w-screen min-h-screen sm:dark:text-black text-white gradient-custom-dark">
          <div className="hidden sm:block">
            <LateralBar />
          </div>
          <div className="block sm:hidden">
            <Menu />
          </div>
          <div className="bg-texture bg-no-repeat h-screen w-full sm:bg-right bg-more-right bg-[size:110%] sm:bg-[size:40%] ">
            <div className="sm:block hidden">
              <Header />
            </div>
            <div className="flex flex-col ml-7 pt-40 sm:ml-36 xl:ml-72 sm:pt-24 xl:pt-52 gap-5 sm:gap-10 w-60 sm:w-96 xl:w-[500px]">
            {children}
            </div>
            <div className="absolute bottom-0">
              <Footer />
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
